version: "3"

services:
  graphql-api:
    build: .
    depends_on:
      - database
      - adminer
    env_file:
      - ./.env
    ports:
      - 3010:3010
    stdin_open: true
    tty: true
    volumes:
      - ./:/api-graphql

  database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=toto90
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=toto90
      - MARIADB_DATABASE=bookmark_db

  adminer:
    image: adminer
    ports:
      - 8080:8080
